/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructuras.ArbolHuffman;
import Estructuras.LS_CaminoCorto;
import Estructuras.grafoRutas;
import static Estructuras.grafoRutas.CaminoCorto;
import static Extra.Listas.BC;
import static Extra.Listas.conduc;
import static Extra.Listas.tabl;
import Nodos.nodoCaminoCorto;
import Nodos.nodoViaje;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.SimpleAttributeSet;

/**
 *
 * @author Audrie
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnViajes = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnConductores = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnRuta = new javax.swing.JButton();
        btnEstructuraC = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnDtopViajes = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        btnDtopclientes = new javax.swing.JButton();
        btnDtopConductores = new javax.swing.JButton();
        btnDtopVehiculos = new javax.swing.JButton();

        jLabel1.setText("Ruta del Archivo de Entrada:");

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnViajes.setText("TOP VIAJES");
        btnViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesActionPerformed(evt);
            }
        });

        btnClientes.setText("TOP CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnConductores.setText("TOP CONDUCTORES");
        btnConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConductoresActionPerformed(evt);
            }
        });

        btnVehiculos.setText("TOP VEHÍCULOS");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });

        btnRuta.setText("RUTA DE UN VIAJE");
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });

        btnEstructuraC.setText("ESTRUCTURA COMPLETA");
        btnEstructuraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstructuraCActionPerformed(evt);
            }
        });

        jLabel2.setText("Ruta del Archivo de Entrada:");

        btnDtopViajes.setText("Descomprimir TopViajes");
        btnDtopViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDtopViajesActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar Menú");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        btnDtopclientes.setText("Descomprimir Top Clientes");
        btnDtopclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDtopclientesActionPerformed(evt);
            }
        });

        btnDtopConductores.setText("Descomprimir Top Conductores");
        btnDtopConductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDtopConductoresActionPerformed(evt);
            }
        });

        btnDtopVehiculos.setText("Descomprimir Top Vehículos");
        btnDtopVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDtopVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEstructuraC, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDtopVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDtopConductores, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(btnDtopclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDtopViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnEstructuraC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDtopViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDtopclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDtopConductores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDtopVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        try {
             String ruta = "TopViajes.edd";
            File file = new File(ruta);
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            grafoRutas grafo = new grafoRutas();
            LS_CaminoCorto Lista = grafo.OrdenarLista(CaminoCorto);
            String Texto="";
            if(Lista !=null){
                nodoCaminoCorto Ini= Lista.getInicio();
                nodoCaminoCorto aux=Ini;
                int i=0;
                do{                    
                    Texto+=aux.toString()+"\n";
                    aux=aux.sig;
                    i++;
                }while(aux!= null && i<10);
            }
            System.out.println(Texto);
            String TextoComprimido=ArbolHuffman.comprimirHuffman(Texto, "TopViajesDescomprimido");
            bw.write(TextoComprimido);
            System.out.println(TextoComprimido);
            bw.close();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Error al generar el top Viajes, "+e);
        }
        
    }//GEN-LAST:event_btnViajesActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.setVisible(false);
        Principal pri = new Principal();
        pri.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        try {
            String llave=JOptionPane.showInputDialog("Favor ingrese llave:");
            nodoViaje Viaje =BC.Buscar(llave);
            if(!Viaje.equals(null)){
                Viaje.getPtrRutaSimple().getLstNodosDetino().GraficarCaminoMin();
            }
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRutaActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        tabl.ImprimirArray();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConductoresActionPerformed
        conduc.ImprimirArray();
    }//GEN-LAST:event_btnConductoresActionPerformed

    private void btnEstructuraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstructuraCActionPerformed
        BC.GraficaGeneral();
    }//GEN-LAST:event_btnEstructuraCActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        BC.ImprimirArray();
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser select = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Solo TXT", "txt");

        select.setFileFilter(filtro);

        select.setDialogTitle("SOLO TXT");
        select.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        select.showOpenDialog(this);
        File archivo = select.getSelectedFile();
        if ((archivo == null) || (archivo.getName().equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "Archivo invalido");
        }
        try {
            String path = archivo.getAbsolutePath();
            String contenido = getArchivo(path);
            jTextField1.setText(path);

            String[] linea = contenido.split("\n");
            SimpleAttributeSet attrs = new SimpleAttributeSet();

            for (int i = 0; i < linea.length; i++) {
                String[] linea1 = linea[i].split(";");
                for (int j = 0; j < linea1.length; j++) {
                    String[] lineaGuarda = linea1[j].split(",");
                    if (lineaGuarda.length == 7) {

                        String dpi = lineaGuarda[0];
                        String Nombre = lineaGuarda[1];
                        String Apellidos = lineaGuarda[2];
                        String Genero = lineaGuarda[3];
                        String Fecha = lineaGuarda[4];
                        int Telefono = Integer.parseInt(lineaGuarda[5]);
                        String Direccion = lineaGuarda[6];
                        tabl.Insertar(dpi, Nombre, Apellidos, Genero, Fecha, Telefono, Direccion);
                    }

                }
            }

            JOptionPane.showMessageDialog(null, "Archivo cargado correctamente.");
            System.out.println("-------------------------------CLIENTES FIN--------------------------------");

        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDtopViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDtopViajesActionPerformed
        JFileChooser select = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Solo edd", "edd");

        select.setFileFilter(filtro);

        select.setDialogTitle("SOLO edd");
        select.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        select.showOpenDialog(this);
        File archivo = select.getSelectedFile();
        if ((archivo == null) || (archivo.getName().equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "Archivo invalido");
        }        
        JOptionPane.showMessageDialog(null, "Archivo cargado correctamente.");
        try {
            String path = archivo.getAbsolutePath();
            String contenido = getArchivo(path);
            jTextField1.setText(path);
            System.out.println(contenido);
            String texto= ArbolHuffman.Descomprimir(contenido, "TopViajesDescomprimido");   //ES AQUÍ, EL MÉTODO QUE DESCOMPRIME
            System.out.println(texto);
            ArbolHuffman.GenerarReporteDescomprimido(texto, "TopViajesDescomprimido");

            

        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnDtopViajesActionPerformed

    private void btnDtopclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDtopclientesActionPerformed
         JFileChooser select = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Solo edd", "edd");

        select.setFileFilter(filtro);

        select.setDialogTitle("SOLO edd");
        select.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        select.showOpenDialog(this);
        File archivo = select.getSelectedFile();
        if ((archivo == null) || (archivo.getName().equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "Archivo invalido");
        }        
        JOptionPane.showMessageDialog(null, "Archivo cargado correctamente.");
        try {
            String path = archivo.getAbsolutePath();
            String contenido = getArchivo(path);
            jTextField1.setText(path);
            System.out.println(contenido);
            String texto= ArbolHuffman.Descomprimir(contenido, "TopClientesDescomprimido");
            System.out.println(texto);
            ArbolHuffman.GenerarReporteDescomprimido(texto, "TopClientesDescomprimido");

            

        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnDtopclientesActionPerformed

    private void btnDtopConductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDtopConductoresActionPerformed
         JFileChooser select = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Solo edd", "edd");

        select.setFileFilter(filtro);

        select.setDialogTitle("SOLO edd");
        select.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        select.showOpenDialog(this);
        File archivo = select.getSelectedFile();
        if ((archivo == null) || (archivo.getName().equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "Archivo invalido");
        }        
        JOptionPane.showMessageDialog(null, "Archivo cargado correctamente.");
        try {
            String path = archivo.getAbsolutePath();
            String contenido = getArchivo(path);
            jTextField1.setText(path);
            System.out.println(contenido);
            String texto= ArbolHuffman.Descomprimir(contenido, "TopConductoresDescomprimido");
            System.out.println(texto);
            ArbolHuffman.GenerarReporteDescomprimido(texto, "TopConductoresDescomprimido");

            

        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnDtopConductoresActionPerformed

    private void btnDtopVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDtopVehiculosActionPerformed
         JFileChooser select = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Solo edd", "edd");

        select.setFileFilter(filtro);

        select.setDialogTitle("SOLO edd");
        select.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        select.showOpenDialog(this);
        File archivo = select.getSelectedFile();
        if ((archivo == null) || (archivo.getName().equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "Archivo invalido");
        }        
        JOptionPane.showMessageDialog(null, "Archivo cargado correctamente.");
        try {
            String path = archivo.getAbsolutePath();
            String contenido = getArchivo(path);
            jTextField1.setText(path);
            System.out.println(contenido);
            String texto= ArbolHuffman.Descomprimir(contenido, "TopVehiculosDescomprimido");
            System.out.println(texto);
            ArbolHuffman.GenerarReporteDescomprimido(texto, "TopVehiculosDescomprimido");

            

        } catch (Exception e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_btnDtopVehiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    public String getArchivo(String ruta) {

        FileReader fr = null;
        BufferedReader br = null;
        String contenido = "";
        try {
            fr = new FileReader(ruta);
            br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {
                contenido += linea + "\n";
            }
        } catch (Exception ex) {

        } finally {
            try {
                br.close();
            } catch (Exception ex) {

            }
        }
        return contenido;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConductores;
    private javax.swing.JButton btnDtopConductores;
    private javax.swing.JButton btnDtopVehiculos;
    private javax.swing.JButton btnDtopViajes;
    private javax.swing.JButton btnDtopclientes;
    private javax.swing.JButton btnEstructuraC;
    private javax.swing.JButton btnRuta;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JButton btnViajes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
